name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        npm install
        npm run build

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: your-hostinger-domain.com
        username: your-username
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /path/to/your/project
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:cache
